version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[npm] "
      include: "scope"
    ignore:
      - dependency-name: "next"
      - dependency-name: "react"
      - dependency-name: "react-dom"

    - package-ecosystem: "docker"
      directory: "/"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[docker] "