on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "next"
